version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      # Mount source code for hot reloading
      - ./:/app
      # Prevent node_modules from being overwritten by the volume mount
      - /app/node_modules
    restart: unless-stopped
    env_file:
      - .env
